name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Buildozer and dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip git zip openjdk-17-jdk
        pip install buildozer cython

    - name: Build APK
      run: |
        buildozer init
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: Justice-APK
        path: bin/*.apk
